services:
  - type: web
    name: talent-pulse-api
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: talentpulse-db
          property: connectionString
      - key: Gemini__ApiKey
        sync: false
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

databases:
  - name: talentpulse-db
    databaseName: talentpulsedb
    user: talentpulse_user
    plan: free
