services:
  - type: web
    name: talent-pulse-api
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: talentpulse-db
          property: connectionString
      - key: Gemini__ApiKey
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        value: talentpulse-api
      - key: Jwt__Audience
        value: talentpulse-client
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: FrontendUrl
        value: https://talent-pulse-ai-six.vercel.app

databases:
  - name: talentpulse-db
    databaseName: talentpulsedb
    user: talentpulse_user
    plan: free
