// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TalentPulseApi.Data;

#nullable disable

namespace TalentPulseApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802111948_AddAuthToUser")]
    partial class AddAuthToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TalentPulseApi.Models.AtsAnalysis", b =>
                {
                    b.Property<Guid>("AtsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JdId")
                        .HasColumnType("uuid");

                    b.Property<int>("MatchScore")
                        .HasColumnType("integer");

                    b.Property<string>("MissingKeywordsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SkillBreakdownJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AtsId");

                    b.HasIndex("JdId");

                    b.HasIndex("ResumeId");

                    b.ToTable("AtsAnalyses");
                });

            modelBuilder.Entity("TalentPulseApi.Models.CandidateAnswer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("FillerWordCount")
                        .HasColumnType("integer");

                    b.Property<string>("IdealAnswerSample")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranscribedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("CandidateAnswers");
                });

            modelBuilder.Entity("TalentPulseApi.Models.FeedbackScorecard", b =>
                {
                    b.Property<Guid>("ScorecardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionPlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CommunicationScore")
                        .HasColumnType("double precision");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ProblemSolvingScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<double>("StarMethodScore")
                        .HasColumnType("double precision");

                    b.Property<double>("TechnicalDepthScore")
                        .HasColumnType("double precision");

                    b.HasKey("ScorecardId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("FeedbackScorecards");
                });

            modelBuilder.Entity("TalentPulseApi.Models.InterviewQuestion", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetSkill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionId");

                    b.HasIndex("SessionId");

                    b.ToTable("InterviewQuestions");
                });

            modelBuilder.Entity("TalentPulseApi.Models.InterviewSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("AtsId");

                    b.HasIndex("UserId");

                    b.ToTable("InterviewSessions");
                });

            modelBuilder.Entity("TalentPulseApi.Models.JobDescription", b =>
                {
                    b.Property<Guid>("JdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredSkillsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JdId");

                    b.ToTable("JobDescriptions");
                });

            modelBuilder.Entity("TalentPulseApi.Models.Resume", b =>
                {
                    b.Property<Guid>("ResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ParsedSkillsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ResumeId");

                    b.HasIndex("UserId");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("TalentPulseApi.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TalentPulseApi.Models.AtsAnalysis", b =>
                {
                    b.HasOne("TalentPulseApi.Models.JobDescription", "JobDescription")
                        .WithMany("AtsAnalyses")
                        .HasForeignKey("JdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentPulseApi.Models.Resume", "Resume")
                        .WithMany("AtsAnalyses")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDescription");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("TalentPulseApi.Models.CandidateAnswer", b =>
                {
                    b.HasOne("TalentPulseApi.Models.InterviewQuestion", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("TalentPulseApi.Models.CandidateAnswer", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TalentPulseApi.Models.FeedbackScorecard", b =>
                {
                    b.HasOne("TalentPulseApi.Models.InterviewSession", "Session")
                        .WithOne("Scorecard")
                        .HasForeignKey("TalentPulseApi.Models.FeedbackScorecard", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TalentPulseApi.Models.InterviewQuestion", b =>
                {
                    b.HasOne("TalentPulseApi.Models.InterviewSession", "Session")
                        .WithMany("Questions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TalentPulseApi.Models.InterviewSession", b =>
                {
                    b.HasOne("TalentPulseApi.Models.AtsAnalysis", "AtsAnalysis")
                        .WithMany()
                        .HasForeignKey("AtsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentPulseApi.Models.User", "User")
                        .WithMany("InterviewSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtsAnalysis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalentPulseApi.Models.Resume", b =>
                {
                    b.HasOne("TalentPulseApi.Models.User", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalentPulseApi.Models.InterviewQuestion", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("TalentPulseApi.Models.InterviewSession", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Scorecard");
                });

            modelBuilder.Entity("TalentPulseApi.Models.JobDescription", b =>
                {
                    b.Navigation("AtsAnalyses");
                });

            modelBuilder.Entity("TalentPulseApi.Models.Resume", b =>
                {
                    b.Navigation("AtsAnalyses");
                });

            modelBuilder.Entity("TalentPulseApi.Models.User", b =>
                {
                    b.Navigation("InterviewSessions");

                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
